name: AWSCredentialsFile


on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-up:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate against AWS docker registry
        run: sed -i "s/AWS_DEFAULT_REGION/${{ secrets.AWS_DEFAULT_REGION }}/g" ./.aws/config && sed -i "s/AWS_ACCESS_KEY_ID/${{ secrets.AWS_ACCESS_KEY_ID }}/g" ./.aws/credentials && sed -i "s#AWS_SECRET_ACCESS_KEY#${{ secrets.AWS_SECRET_ACCESS_KEY }}#g" ./.aws/credentials
  