name: AWSEBSDeploy


on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string     
      environment_name:
        required: true
        type: string
      region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-up:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yml
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ inputs.application_name }}
          environment_name: ${{ inputs.environment_name }}
          version_label: ${{ steps.current-time.outputs.time }}
          region: ${{ inputs.region }}
          deployment_package: deploy.zip
