name: SeleniumTest

on:
  workflow_call:
    inputs:
      driver:
        required: true
        type: string     
      port:
        required: true
        type: string
      scriptPath:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      APP_USERNAME:
        required: true
      APP_PASSWORD:
        required: true

jobs:
  selenium-test:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-${{ inputs.driver }}
        ports:
          - ${{ inputs.port }}:4444
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.8
      - name: Initialize terraform
        run: sh ./scripts/terraform/test-env/init.sh
      - name: Authenticate against docker registry
        run: sh ./scripts/docker/authenticate.sh
      - name: Run QTAF Tests on Selenium
        run:  USERNAME=${{ secrets.APP_USERNAME }} PASSWORD=${{ secrets.APP_PASSWORD }} sh ${{ inputs.scriptPath }}
      - name: Upload logs to S3
        run: DRIVER_NAME=${{ inputs.driver }} USERNAME=${{ secrets.APP_USERNAME }} PASSWORD=${{ secrets.APP_PASSWORD }} sh ./scripts/tests/logs/upload_qtaf_logs.sh
