name: TerraformApply


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string     
      chdir:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-apply:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ inputs.version }}
      - name: Initialize terraform
        run: terraform -chdir=${{ inputs.chdir }} init
      - name: Apply configuration
        run: terraform -chdir=${{ inputs.chdir }} apply -auto-approve
