name: TerraformDestroy


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string     
      chdir:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

jobs:
  terraform-up:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.version }}
      - name: Initialize terraform
        run: terraform -chdir=${{ inputs.chdir }} init
      - name: Destroy configuration
        run: terraform -chdir=${{ inputs.chdir }} destroy -auto-approve
